[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "module"
version = "19.43.41"
excluded-patches = "'Seekbar thumbnails' 'Swipe controls' 'GmsCore support'"
